# Xamarin
# Provision Xcode test YML

variables:
  azure_build_url: '$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'
  macOSVersion: 'Hosted Mac Internal Mojave'

jobs:
- job: macOS
  displayName: Provision Xcode
  timeoutInMinutes: 30
  strategy:
    matrix:
      # We have rougly 900 tests, which take a while to build for device.
      # So in that case, we split them in 3 buckets of roughly 300 tests each,
      # based on the first letter of the project's filename.
      A:
        MODE: 'A'
      B:
        MODE: 'B'

  pool:
    name: '$(macOSVersion)'

  steps:
  - checkout: self
    persistCredentials: true

  - bash: ./tools/devops/system-info.sh
    displayName: System Info

  - task: provisionator@2
    displayName: Provision Xcode
    inputs:
      provisionator_uri: '$(provisionator-uri)'
      github_token: '$(github-pat)'
      provisioning_script: $(System.DefaultWorkingDirectory)/tools/devops/provision-xcode.csx

  - bash: ./tools/devops/system-info.sh
    displayName: System Info post provisioning

