# Xamarin
#
# The following templates contains all the different steps that can be used to consume the tests results from a 
# matrix job and will unzip the pipeline artifacts and upload the results to VSTS 
#
# The template takes the following env vars
#
# CONTEXT: The context that is used to set the status of the commit.

steps:
###
### Download all test summaries
###

- task: DownloadPipelineArtifact@2
  displayName: Download test summaries
  inputs:
    patterns: '**/TestSummary*'
    allowFailedBuilds: true
    path: $(Pipeline.Workspace)/Summaries

- bash: |
    set -x
    set -e
    ls -la
    ls -la $PIPELINE_WORKSPACE
    ls -la $PIPELINE_WORKSPACE/Summaries
    pwd
    #cat $PIPELINE_WORKSPACE/Summaries/TestSummary-*/TestSummary-*.md >> ./TestSummary.md

    for f in $PIPELINE_WORKSPACE/Summaries/TestSummary-*/TestSummary.md;

    prefix="${PIPELINE_WORKSPACE}/Summaries/"
    prefix_len = ${#prefix}
    echo $prefix_len
    suffix = "/TestSummary.md"
    suffix_len = ${#suffix}
    echo $suffix_len

    s=${f:$prefix_len}
    echo $s
    s_len=${#s}
    diff=$((s_len - suffix_len))

    echo $diff
    s=${s:0:$diff}
    echo $s

    do echo $s >> ./TestSummary.md
    cat $f >> ./TestSummary.md
    done

    cat ./TestSummary.md
  displayName: 'Merge TestSummary files'

###
### Publish merged TestSummary file
###
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: Aggregate TestSummary'
  inputs:
#    targetPath: 'xamarin-macios/tests/TestSummary.md'
    targetPath: ./TestSummary.md
    artifactName: TestSummary
    continueOnError: true

# pwsh for PowerShell Core
# powershell is for Win PowerShell
- pwsh: ./tools/devops/templates/publish_results.ps1
  condition: succeededOrFailed()
  env:
    BUILD_REVISION: $(BUILD_REVISION)
    GH_STATE: $(GH_STATE)
    GITHUB_TOKEN: $(GitHub.Token)
    CONTEXT: $(CONTEXT)

###
### Report final results to GitHub
###

- bash: ./jenkins/vsts-device-tests-set-status.sh "--token=$(GitHub.Token)" --device="VSTS-DDFun"
  displayName: Report results to GitHub as comment / status
  continueOnError: true
  condition: succeededOrFailed()
