# Xamarin
#
# The following templates contains all the different steps that can be used to consume the tests results from a 
# matrix job and will unzip the pipeline artifacts and upload the results to VSTS 
#
# The template takes the following env vars
#
# CONTEXT: The context that is used to set the status of the commit.

steps:
###
### Download all test summaries
###

- task: DownloadPipelineArtifact@2
  displayName: Download test summaries
  inputs:
    patterns: '**/TestSummary*'
    allowFailedBuilds: true
    path: $(Pipeline.Workspace)/Summaries

- bash: |
    set -x
    set -e
    ls -la
    ls -la $PIPELINE_WORKSPACE
    ls -la $PIPELINE_WORKSPACE/Summaries
    pwd
    cat $PIPELINE_WORKSPACE/Summaries/TestSummary-*.md >> ./TestSummary.md
    cat ./TestSummary.md
  displayName: 'Merge TestSummary files'

###
### Publish merged TestSummary file
###
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: Aggregate TestSummary'
  inputs:
#    targetPath: 'xamarin-macios/tests/TestSummary.md'
    targetPath: ./TestSummary.md
    artifactName: TestSummary
    continueOnError: true

# pwsh for PowerShell Core
# powershell is for Win PowerShell
- pwsh: ./tools/devops/templates/publish_results.ps1
  condition: succeededOrFailed()
  env:
    BUILD_REVISION: $(BUILD_REVISION)
    GH_STATE: $(GH_STATE)
    GITHUB_TOKEN: $(GitHub.Token)
    CONTEXT: $(CONTEXT)

#  VSTS_BUILD_URL='https://dev.azure.com/devdiv/ - SYSTEM_TEAMFOUNDATIONSERVERURI
# DevDiv/_build/index?buildId=3521765&view=ms.vss-test-web.test-result-details'
#VSTS_BUILD_URL="${SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${SYSTEM_TEAMPROJECT}/_build/index?buildId=${BUILD_BUILDID}&view=ms.vss-test-web.test-result-details"
# 	printf "\t\"state\": \"%s\",\n" "$STATE"
#	printf "\t\"target_url\": \"%s\",\n" "$TARGET_URL"
#	printf "\t\"description\": %s,\n" "$(echo -n "$DESCRIPTION" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))')"
#	printf "\t\"context\": \"%s\"\n" "$CONTEXT"
# ./jenkins/add-commit-status.sh --token="$TOKEN" --hash="$BUILD_REVISION" --state="$GH_STATE" --target-url="$VSTS_BUILD_URL" --description="$DESCRIPTION" --context="VSTS: device tests ($DEVICE_TYPE)"


###
### Report final results to GitHub
###

- bash: ./jenkins/vsts-device-tests-set-status.sh "--token=$(GitHub.Token)" --device="VSTS-DDFun"
  displayName: Report results to GitHub as comment / status
  continueOnError: true
  condition: succeededOrFailed()
