# Xamarin
#
# The following templates contains all the different steps that can be used to consume the tests results from a 
# matrix job and will unzip the pipeline artifacts and upload the results to VSTS 
#
# The template takes the following env vars
#
# CONTEXT: The context that is used to set the status of the commit.

steps:

### 
### Get the array of .zip result files and extract them so that we can find the test results.
###

- task: DownloadPipelineArtifact@2
  displayName: 'Download Jobs Tests Results'
  inputs:
    patterns: '**/*.zip'

- task: ExtractFiles@1
  displayName: 'Extract Tests Results'
  inputs:
    archiveFilePatterns: '**/*.zip' 
    destinationFolder: tests_results
    cleanDestinationFolder: true 
    
###
### Upload the xml results to vsts.
###

- task: PublishTestResults@2
  displayName: 'Publish NUnit Device Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/nunit-test-*.xml'
    failTaskOnFailedTests: true
  continueOnError: true
  condition: succeededOrFailed()
