# Xamarin
# Create code backups

resources:
  repositories:
  - repository: maccore
    type: github
    name: xamarin/maccore
    ref: refs/heads/main
    endpoint: xamarin
  - repository: SubmissionSamples
    type: github
    name: xamarin/SubmissionSamples
    ref: refs/heads/main
    endpoint: xamarin
  - repository: XmlDocSync
    type: github
    name: xamarin/XmlDocSync
    ref: refs/heads/main
    endpoint: xamarin
  - repository: ios-api-docs
    type: github
    name: xamarin/ios-api-docs
    ref: refs/heads/main
    endpoint: xamarin
  - repository: mac-api-docs
    type: github
    name: xamarin/mac-api-docs
    ref: refs/heads/main
    endpoint: xamarin
  - repository: xamarin-analysis
    type: github
    name: xamarin/xamarin-analysis
    ref: refs/heads/main
    endpoint: xamarin

variables:
  - group: xamops-azdev-secrets
  - group: Xamarin Release
  - group: Xamarin-Secrets

jobs:
- job: backup_code 
  displayName: Backup xamarin-macios code 
  timeoutInMinutes: 1000

  pool:
    name: 'VSEngDeploymentPool'
    workspace:
      clean: all

  steps:
  - checkout: self
    clean: true
  - checkout: maccore
    persistCredentials: true
    clean: true

  - powershell: |
      Get-ChildItem
      Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\backup\scripts\Backup.psm1
      if (Test-Path "backups") {
          Remove-Item -LiteralPath backups -Force -Recurse
      }
      New-Item -Name backups -ItemType directory
      New-XamarinMaciosBackup
      Set-Location -Path .. 
      mv working-dir/*-bundle backups
    displayName: 'Create backups'
    condition: always()

  - task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
    displayName: 'Publish to Artifact Services Drop'
    inputs:
      dropServiceURI: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'
      buildNumber: 'xamarin-macios/backups/$(Build.BuildNumber)/$(Build.BuildId)'
      sourcePath: backups
      detailedLog: true
      usePat: true 