# YAML pipeline build definition
# https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=13760&view=Tab_Tasks
#
# YAML build pipeline based on the Jenkins multi-stage (main branch) build workflow
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/job/main/
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/configure
#
resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/dev/bond/keychain                      # UNDONE: Change back to main once keychain diagnostics change has been merged (or not)
    endpoint: xamarin

  - repository: maccore
    type: github
    name: xamarin/maccore
    ref: refs/heads/yaml-pipeline-device-tests            # UNDONE: Change back to main once the keychain search list fix has merged to main
    endpoint: xamarin

  - repository: release-scripts
    type: github
    name: xamarin/release-scripts
    ref: refs/heads/sign-and-notarized 
    endpoint: xamarin

variables:
- group: xamops-azdev-secrets
- group: Xamarin-Secrets
- group: Xamarin Signing
- group: Xamarin Release
- group: Xamarin Notarization
- group: XamarinCompatLab                                     # provisionator-uri setting
- name: GitHub.Token                                          # Override the GitHub.Token setting defined in the Xamarin Release group
  value: $(github--pat--vs-mobiletools-engineering-service2)  # Use a token dedicated to critical production workflows and help avoid GitHub throttling
- name: system.debug
  value: true
- name: SigningKeychain
  value: "builder.keychain"
- name: OSX_KEYCHAIN_PASS                                     # UNDONE: Override the OSX_KEYCHAIN_PASS to use same password as used by the iOS mac pool machines
  value: $(ios-pool-keychain-password)
- name: VSDropsPrefix
  value: 'https://vsdrop.corp.microsoft.com/file/v1/xamarin-macios/device-tests'
- name: USE_TCP_TUNNEL                                        # Needed to ensure that devices uses the usb cable to communicate with the devices to run the tests.
  value: true

trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - d16-*

stages:

- stage: configure
  displayName: 'Configure'
  jobs:
  - job: pipeline_configuration
    pool:
      vmImage: ubuntu-latest
    steps:
      # TODO: do parse labels 
      - bash: |
          echo '##vso[task.setvariable variable=runSimulator;isOutput=true]true'
          echo '##vso[task.setvariable variable=runDevice32b;isOutput=true]false'
          echo '##vso[task.setvariable variable=runDevice64b;isOutput=true]true'
          echo '##vso[task.setvariable variable=runDeviceTv;isOutput=true]true'
          echo '##vso[task.setvariable variable=runSamples;isOutput=true]false'
        displayName: 'Parse labels'
        name: labels

- stage: governance_checks
  displayName: 'Governance Checks'
  dependsOn: []
  jobs:
    - job: governance
      displayName: 'Governance Checks'
      pool:
        vmImage: windows-latest
      steps:
      - template: templates/governance-checks.yml

- stage: build_packages
  displayName: 'Build'
  dependsOn: configure
  jobs:
  - job: build
    displayName: 'Build packages'
    timeoutInMinutes: 1000
    pool:
      name: VSEng-Xamarin-RedmondMacCatalinaBuildPool-iOS-Untrusted
      demands:
      - Agent.OS -equals Darwin
      - Agent.OSVersion -equals 10.15
    workspace:
      clean: all

    steps:
    - template: templates/build-packages.yml

  - job: upload_azure_blob
    displayName: 'Upload packages to Azure'
    timeoutInMinutes: 1000
    dependsOn: build # can start as soon as the tests are done
    condition: succeeded()

    variables:
      Parameters.outputStorageUri: ''

    pool:
      name: VSEngDeploymentPool
      demands: agent.os -equals Windows_NT # we need to use a windows machine since vsdrops just works on them and the pool might have diff OS in the agents
      workspace:
        clean: all
    steps:
    - template: templates/upload-azure.yml

  # ideally we would use a matrix here, like:
  #  - job: device_tests
  #    displayName: 'Device tests'
  #    timeoutInMinutes: 1000
  #
  #    strategy:
  #      matrix:
  #        iOS32: # TODO: This bots should be moved to the ddfun pool
  #          deviceDemands: 'xismoke-32'
  #          testsLabels: '--label=run-ios-32-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
  #          poolName: 'VSEng-Xamarin-QA'
  #        iOS64:
  #          deviceDemands: 'ios'
  #          testsLabels: '--label=run-ios-64-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
  #          poolName: 'VSEng-Xamarin-Mac-Devices'
  #        tvOS:
  #          deviceDemands: 'tvos'
  #          testsLabels: '--label=run-tvos-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
  #          poolName: 'VSEng-Xamarin-Mac-Devices'
  #
  #    pool:
  #      name: $(poolName)
  #      demands: $(deviceDemands)
  #      workspace:
  #        clean: all
  #
  #    steps:
  #    - template: templates/device-tests.yml
  #
  # Unfortunally, variable expansion will not happen on the right time, and will result in an agent error, to fix that
  # we use a template for the test and we set each of the jobs. Not ideal, but is only a 3 jobs matrix

- template: templates/device-tests-stage.yml
  parameters:
    devicePrefix: 'simulator'
    execute: 'runSimulator'
    stageName: 'Simulator Tests'
    iOSDevicePool: 'VSEng-Xamarin-RedmondMacCatalinaBuildPool-iOS-Untrusted'
    WindowsDevicePool: 'VSEngDeploymentPool'
    useXamarinStorage: False
    testsLabels: '--label=run-all-tests,skip-device-tests'
    statusContext: 'VSTS: Simulator tests'
    iOSDeviceDemand: 'Agent.OSVersion -equals 10.15' # trick to reuse the device pipeline and add just the mac os x requirement, sneaky :) 
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    keyringPass: $(ios-pool-keychain-password)

- template: templates/device-tests-stage.yml
  parameters:
    devicePrefix: 'ios32b'
    execute: 'runDevice32b'
    stageName: 'iOS32b Device Tests'
    iOSDevicePool: 'VSEng-Xamarin-QA'
    WindowsDevicePool: 'VSEngDeploymentPool'
    useXamarinStorage: False
    testsLabels: '--label=run-ios-32-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
    statusContext: 'VSTS: device tests iOS32b'
    iOSDeviceDemand: 'xismoke-32'
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    keyringPass: $(xma-password)

- template: templates/device-tests-stage.yml
  parameters:
    devicePrefix: 'ios64'
    execute: 'runDevice64b'
    stageName: 'iOS64 Device Tests'
    iOSDevicePool: 'VSEng-Xamarin-Mac-Devices'
    WindowsDevicePool: 'VSEngDeploymentPool'
    useXamarinStorage: False
    testsLabels: '--label=run-ios-64-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
    statusContext: 'VSTS: device tests iOS'
    iOSDeviceDemand: 'ios'
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    keyringPass: $(xma-password)

- template: templates/device-tests-stage.yml
  parameters:
    devicePrefix: 'tvos'
    execute: 'runDeviceTv'
    stageName: 'tvOS Device Tests'
    iOSDevicePool: 'VSEng-Xamarin-Mac-Devices'
    WindowsDevicePool: 'VSEngDeploymentPool'
    useXamarinStorage: False
    testsLabels: '--label=run-tvos-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
    statusContext: 'VSTS: device tests tvOS'
    iOSDeviceDemand: 'tvos'
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    keyringPass: $(xma-password)

- stage: mac_mojave_tests
  displayName : 'Mac Mojave Tests'
  dependsOn: build_packages
  jobs:
  - template: templates/mac-tests.yml
    parameters:
      macPool: 'Hosted Mac Internal Mojave'

- stage: mac_sierra_tests
  displayName : 'Mac High Sierra Tests'
  dependsOn: build_packages
  jobs:
  - template: templates/mac-tests.yml
    parameters:
      macPool: 'Hosted Mac Internal'

# TODO: Not the real step
- stage: sample_testing
  displayName: 'Sample testing'
  dependsOn:
  - configure
  - build_packages
  jobs:
  - job: sample_testing
    pool:
      vmImage: ubuntu-latest
    steps:
      # TODO: do parse labels 
      - bash: |
          echo "Samples!"
        displayName: 'Sample testing'